version: '3.6'

services:
    claims_api:
        build: 
            context: .
            dockerfile: OrdersApi.Dockerfile
        ports:
            - "5000:80"
        depends_on:
            - sqldata
            - rabbitmq
        environment:
            - ConnectionString=Data Source=sqldata;Initial Catalog=Orders;Integrated Security=False;Encrypt=False;User ID=sa;Password=P@ssW0rdTr1ckz
            - RabbitConnectionString=rabbitmq://rabbitmq
    payments_api:
        build:
            context: .
            dockerfile: Payments.WebApi.Dockerfile
        ports:
            - "5004:80"
        depends_on:
            - sqldata
            - rabbitmq
        environment:
            - ConnectionString=Data Source=sqldata;Initial Catalog=Payments;Integrated Security=False;Encrypt=False;User ID=sa;Password=P@ssW0rdTr1ckz
            - RabbitConnectionString=rabbitmq://rabbitmq
    sqldata:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "P@ssW0rdTr1ckz"
            ACCEPT_EULA: "Y"
        ports:
        - "1433:1433"   
    rabbitmq:
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=P@ssW0rdTr1ckz
        image: rabbitmq:3-management
